version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - CUSTOM_FOOTER=${CUSTOM_FOOTER}
      - MDISK_TOKEN=${MDISK_TOKEN}